spring:
  application:
    name: Spring boot Liquibase Demo
  profiles:
    active: '@activeProfile@'
  liquibase:
    change-log: classpath:db/db.changelog-${spring.profiles.active}.xml
  datasource:
    url: @liquibase.url@
    username: @liquibase.username@
    password: @liquibase.password@
    driver-class-name: org.h2.Driver
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always