spring:
  jpa:
    hibernate:
      ddl-auto: update #need this one for persistent db only
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:/tmp/spring-boot-h2;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
debug: true