spring:
  jpa:
    hibernate:
      ddl-auto: update #need this one for persistent db only
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: false
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always