spring:
  jpa:
    hibernate:
      ddl-auto: none #need this one for persistent db only
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: false